server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: test123
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
          multiplier: 2
          max-interval: 30000